### ISSUE TITLE
proto: all services proto file should be perfected to help with developing

### ISSUE THREAD

**Issue by alilestera** [toomanysource/atreus-old#33]
**What would you like to be added:**

proto files for all services.

**Reference:**

Here are some resources to help you work on this issue.

Project basic information(API definition):
https://bytedance.feishu.cn/docx/BhEgdmoI3ozdBJxly71cd30vnRc

**Comment by intyouss** [comment]
I'm taking this assignment.

**Comment by alilestera** [comment]
@intyouss Thanks for your help!
I assigned it to you.

**Comment by intyouss** [comment]
# Need RPC Service
- Feed
  - IsFavortie 需要 Favorite 根据id和VideoID 返回是否点赞
  - tbd.
- Publish
- Favorite
- Relation
- Comment
- User

**Comment by intyouss** [comment]
**Favorite**

```protobuf
syntax = "proto3";

package api.favorite.service.v1;
import "google/api/annotations.proto";
option go_package = "Atreus/api/favorite/service/v1;v1";

service FavoriteService{
  // 获取喜爱视频列表(客户端)
  rpc GetFavoriteList(FavoriteListRequest) returns (FavoriteListReply){
    option (google.api.http) = {
      get: "/douyin/favorite/list"
    };
  }
  // 取消或添加喜爱视频(客户端)
  rpc FavoriteAction(FavoriteActionRequest) returns (FavoriteActionReply){
    option (google.api.http) = {
      post: "/douyin/favorite/action"
      body: "*"
    };
  }
  // 根据userId和videoId判断是否喜爱(publish)
  rpc IsFavorite(IsFavoriteRequest) returns (IsFavoriteReply) {}
}

message IsFavoriteRequest {
  uint32 user_id = 1; // 用户id
  repeated uint32 video_id = 3; // 视频id
}

message IsFavoriteReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated bool is_favorite = 3; // true-已点赞，false-未点赞
}

message FavoriteListRequest {
  uint32 user_id = 1; // 用户id
  string token = 2; // 用户token
}

message FavoriteListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated Video video_list = 3; // 视频信息列表
}

message FavoriteActionRequest {
  string token = 1; // 用户token
  uint32 video_id = 2; // 视频id
  uint32 action_type = 3; // 1-点赞，2-取消点赞
}

message FavoriteActionReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
}

message Video{
  uint32 id = 1; // 视频唯一标识
  User author = 2; // 视频作者信息
  string play_url = 3; // 视频播放地址
  string cover_url = 4; // 视频封面地址
  uint32 favorite_count = 5; // 视频的点赞总数
  uint32 comment_count = 6; // 视频的评论总数
  bool is_favorite = 7; // true-已点赞，false-未点赞
  string title = 8; // 视频标题
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}
```

**Comment by intyouss** [comment]
**Relation**

```protobuf
syntax = "proto3";

package relation.service.v1;

option go_package = "api/relation/service/v1;v1";
import "google/api/annotations.proto";

service RelationService {
  // 获取粉丝列表(客户端)
  rpc GetFollowerRelationList(RelationFollowerListRequest) returns (RelationFollowerListReply) {
    option (google.api.http) = {
      get: "/douyin/relation/follower/list"
    };
  }
  // 获取关注列表(客户端)
  rpc GetFollowRelationList(RelationFollowListRequest) returns (RelationFollowListReply) {
    option (google.api.http) = {
      get: "/douyin/relation/follow/list"
    };
  }
  // 关注或取关用户(客户端)
  rpc RelationAction(RelationActionRequest) returns (RelationActionReply) {
    option (google.api.http) = {
      post: "/douyin/relation/action"
      body: "*"
    };
  }
  // 根据userId和toUserId判断是否关注(user)
  rpc IsFollow(IsFollowRequest) returns (IsFollowReply) {}
}

message IsFollowRequest {
  uint32 user_id = 1;
  uint32 to_user_id = 2;
}

message IsFollowReply {
  int32 status_code = 1;
  string status_msg = 2;
  bool is_follow = 3;
}

message RelationActionRequest {
  string token = 1; // 用户鉴权token
  uint32 to_user_id = 2; // 对方用户id
  uint32 action_type = 3; // 1-关注，2-取消关注
}

message RelationActionReply{
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
}

message RelationFollowerListRequest {
  uint32 user_id = 1; // 用户id
  string token = 2; // 用户鉴权token
}

message RelationFollowerListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated User user_list = 3; // 用户列表
}

message RelationFollowListRequest {
  uint32 user_id = 1; // 用户id
  string token = 2; // 用户鉴权token
}

message RelationFollowListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated User user_list = 3; // 用户信息列表
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}
```

**Comment by intyouss** [comment]
**Feed**

```protobuf
syntax = "proto3";

package api.feed.service.v1;

import "google/api/annotations.proto";

option go_package = "Atreus/api/feed/service/v1;v1";

service FeedService {
  // 获取最多30个按照最新投稿时间排序的视频列表(客户端)
  rpc GetFeedList(ListFeedRequest) returns (ListFeedReply) {
    option (google.api.http) = {
      get: "/douyin/feed"
    };
  }
}

message ListFeedRequest {
  string latest_time = 1;
  string token = 2;
}

message ListFeedReply {
  int32 status_code = 1;
  string status_msg = 2;
  repeated Video video_list = 3;
  int64 next_time = 4;
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}

message Video {
  uint32 id = 1;
  User author = 2;
  string play_url = 3;
  string cover_url = 4;
  uint32 favorite_count = 5;
  uint32 comment_count = 6;
  bool is_favorite = 7;
  string title = 8;
}
```

**Comment by intyouss** [comment]
**Comment**

```protobuf
syntax = "proto3";

package comment.service.v1;

option go_package = "api/comment/service/v1;v1";
import "google/api/annotations.proto";

service CommentService {
  rpc GetCommentList(CommentListRequest) returns (CommentListReply) {
    option (google.api.http) = {
      get: "/douyin/comment/list"
    };
  }
  rpc CommentAction(CommentActionRequest) returns (CommentActionReply) {
    option (google.api.http) = {
      post: "/douyin/comment/action"
      body: "*"
    };
  }
}

message CommentListRequest {
  string token = 1; // 用户鉴权token
  uint32 video_id = 2; // 视频id
}

message CommentListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated Comment comment_list = 3; // 评论列表
}

message CommentActionRequest {
  string token = 1; // 用户鉴权token
  uint32 video_id = 2; // 视频id
  uint32 action_type = 3; // 1-发布评论，2-删除评论
  string comment_text = 4; // 用户填写的评论内容，在action_type=1的时候使用
  uint32 comment_id = 5; // 要删除的评论id，在action_type=2的时候使用
}

message CommentActionReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  Comment comment = 3; // 评论成功返回评论内容，不需要重新拉取整个列表
}

message Comment {
  uint32 id = 1; // 视频评论id
  User user =2; // 评论用户信息
  string content = 3; // 评论内容
  string create_date = 4; // 评论发布日期，格式 mm-dd
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}
```

**Comment by intyouss** [comment]
**User**

```protobuf
syntax = "proto3";

package user.service.v1;

import "google/api/annotations.proto";

option go_package = "api/user/service/v1;v1";

service UserService {
  rpc UserRegister(UserRegisterRequest) returns (UserRegisterReply) {
    option (google.api.http) = {
      post: "/douyin/user/register"
      body: "*"
    };
  }

  rpc UserLogin(UserLoginRequest) returns (UserLoginReply) {
    option (google.api.http) = {
      post: "/douyin/user/login"
      body: "*"
    };
  }

  rpc GetUserInfo(UserInfoRequest) returns (UserInfoReply) {
    option (google.api.http) = {
      get: "/douyin/user"
    };
  }

  rpc UpdateUserInfo(UpdateUserInfoRequest) returns (UpdateUserInfoReply) {
    option (google.api.http) = {
      post: "/douyin/user/update"
      body: "*"
    };
  }

  rpc GetUserInfos(UserInfosRequest) returns (UserInfosReply);

  rpc UpdateFollow(UpdateFollowRequest) returns (UpdateFollowReply);
  rpc UpdateFollower(UpdateFollowerRequest) returns (UpdateFollowerReply);
  rpc UpdateFavorited(UpdateFavoritedRequest) returns (UpdateFavoritedReply);
  rpc UpdateWork(UpdateWorkRequest) returns (UpdateWorkReply);
  rpc UpdateFavorite(UpdateFavoriteRequest) returns (UpdateFavoriteReply);
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}

message UserInfoRequest {
  uint32 user_id = 1; // 用户id
  string token = 2; // 用户鉴权token
}

message UserInfoReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  User user = 3; // 用户信息
}

message UserLoginRequest {
  string username = 1; // 登录用户名
  string password = 2; // 登录密码
}

message UserLoginReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  uint32 user_id = 3; // 用户id
  string token = 4; // 用户鉴权token
}

message UserRegisterRequest {
  string username = 1; // 注册用户名，最长32个字符
  string password = 2; // 密码，最长32个字符
}

message UserRegisterReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  uint32 user_id = 3; // 用户id
  string token = 4; // 用户鉴权token
}

message UpdateUserInfoRequest {
  string token = 1; // 用户鉴权token
  string name = 2; // 用户名称
  string avatar = 3; //用户头像
  string background_image = 4; //用户个人页顶部大图
  string signature = 5; //个人简介
}

message UpdateUserInfoReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
}

message UserInfosRequest {
  repeated uint32 user_ids = 1; // 用户id列表
}

message UserInfosReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated User users = 3; // 用户信息列表
}

message UpdateFollowRequest {
  uint32 user_id = 1; // 用户id
  int32 follow_change = 2; // 关注数变化值
}

message UpdateFollowReply {
  uint32 user_id = 1; // 用户id
  int32 status_code = 2; // 状态码，0-成功，其他值-失败
  string status_msg = 3; // 返回状态描述
}

message UpdateFollowerRequest {
  uint32 user_id = 1; // 用户id
  int32 follower_change = 2; // 粉丝数变化值
}

message UpdateFollowerReply {
  uint32 user_id = 1; // 用户id
  int32 status_code = 2; // 状态码，0-成功，其他值-失败
  string status_msg = 3; // 返回状态描述
}

message UpdateFavoritedRequest {
  uint32 user_id = 1; // 用户id
  int32 favorited_change = 2; // 获赞数变化值
}

message UpdateFavoritedReply {
  uint32 user_id = 1; // 用户id
  int32 status_code = 2; // 状态码，0-成功，其他值-失败
  string status_msg = 3; // 返回状态描述
}

message UpdateWorkRequest {
  uint32 user_id = 1; // 用户id
  int32 work_change = 2; // 作品数变化值
}

message UpdateWorkReply {
  uint32 user_id = 1; // 用户id
  int32 status_code = 2; // 状态码，0-成功，其他值-失败
  string status_msg = 3; // 返回状态描述
}

message UpdateFavoriteRequest {
  uint32 user_id = 1; // 用户id
  int32 favorite_change = 2; // 点赞数变化值
}

message UpdateFavoriteReply {
  uint32 user_id = 1; // 用户id
  int32 status_code = 2; // 状态码，0-成功，其他值-失败
  string status_msg = 3; // 返回状态描述
}
```

**Comment by mo3et** [comment]
**Publish**

```protobuf
syntax = "proto3";

package publish.service.v1;

option go_package = "api/publish/service/v1;v1";
import "google/api/annotations.proto";

service PublishService {
  // 获取用户投稿视频列表(客户端)
  rpc GetPublishList(PublishListRequest) returns (PublishListReply) {
    option (google.api.http) = {
      get: "/douyin/publish/list"
    };
  }
  // 用户投稿或删除视频(客户端)
  rpc PublishAction(PublishActionRequest) returns (PublishActionReply) {
    option (google.api.http) = {
      post: "/douyin/publish/action"
      body: "*"
    };
  }

  // 获取根据最新投稿时间并根据获取数量进行返回(feed)
  rpc GetVideoList(VideoListRequest) returns (VideoListReply) {}
  // 根据视频id列表获取视频列表(favorite)
  rpc GetVideoListByVideoIds(VideoListByVideoIdsRequest) returns (VideoListReply) {}

  // 更新视频点赞总数(relation)
  rpc UpdateFavorite(UpdateFavoriteCountRequest) returns (UpdateCountReply) {}
  // 更新视频评论总数(comment)
  rpc UpdateComment(UpdateCommentCountRequest) returns (UpdateCountReply) {}

}

message VideoListRequest {
  string latest_time = 1; // 最新视频时间戳
  uint32 number = 2; // 视频数量
}

message VideoListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated Video video_list = 3; // 视频列表
}

message VideoListByVideoIdsRequest {
  repeated uint32 video_id = 1; // 视频id列表
}

message UpdateFavoriteCountRequest {
  uint32 video_id = 1; // 视频id
  int32 favorite_change = 2; // 关注数变化值
}

message UpdateCountReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
}

message UpdateCommentCountRequest {
  uint32 video_id = 1; // 视频id
  int32 comment_change = 2; // 评论数变化值
}

message PublishActionRequest {
  string token = 1; // 用户鉴权token
  bytes data = 2; // 视频数据
  string title = 3; // 视频标题
}

message PublishActionReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
}

message PublishListRequest {
  uint32 user_id = 1; // 用户id
  string token = 2; // 用户鉴权token
}

message PublishListReply {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  repeated Video video_list = 3; // 用户发布的视频列表
}

message Video {
  uint32 id = 1; // 视频唯一标识
  User author = 2; // 视频作者信息
  string play_url = 3; // 视频播放地址
  string cover_url = 4; // 视频封面地址
  uint32 favorite_count = 5; // 视频的点赞总数
  uint32 comment_count = 6; // 视频的评论总数
  bool is_favorite = 7; // true-已点赞，false-未点赞
  string title = 8; // 视频标题
}

message User {
  uint32 id = 1; // 用户id
  string name = 2; // 用户名称
  uint32 follow_count = 3; // 关注总数
  uint32 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  uint32 total_favorited = 9; //获赞数量
  uint32 work_count = 10; //作品数量
  uint32 favorite_count = 11; //点赞数量
}
```

**Comment by Li1Mo0N** [comment]
> ```proto
> PublishAction
> ```

1. The PublishActionReplay in the PublishAction service was written incorrectly.
2. The video_list field in the message PublishListReply should be repeated

**Comment by alilestera** [comment]
> > ```proto
> > PublishAction
> > ```
> 
> 1. The PublishActionReplay in the PublishAction service was written incorrectly.
> 2. The video_list field in the message PublishListReply should be repeated

@Li1Mo0N You are right!

@Mo3et 
You could modify your reply.

**Comment by mo3et** [comment]
> > ```proto
> > PublishAction
> > ```
> 
> 1. The PublishActionReplay in the PublishAction service was written incorrectly.
> 2. The video_list field in the message PublishListReply should be repeated

You can upload the code to [gist](https://gist.github.com/) and say the diff.

And I fixed the error.

**Comment by Li1Mo0N** [comment]
> > > ```proto
> > > PublishAction
> > > ```
> > 
> > 
> > 
> > 1. The PublishActionReplay in the PublishAction service was written incorrectly.
> > 2. The video_list field in the message PublishListReply should be repeated
> 
> You can upload the code to [gist](https://gist.github.com/) and say the diff.
> 
> And I fixed the error.

You forgot to modify the name of the message PublishActionReplay below

**Comment by mo3et** [comment]
> You forgot to modify the name of the message PublishActionReplay below

Now Fixed.

**Comment by FirwoodLin** [comment]
```proto
  int64 favorite_count = 5; // 视频的点赞总数
  int64 comment_count = 6; // 视频的评论总数
```

in favorite proto, there are some flaws. In the defination of `Video`, the data types of  fields `count`  should be corrected to `uint32`.

**Comment by intyouss** [comment]
> ```proto
>   int64 favorite_count = 5; // 视频的点赞总数
>   int64 comment_count = 6; // 视频的评论总数
> ```
> 
> in favorite proto, there are some flaws. In the defination of `Video`, the data types of fields `count` should be corrected to `uint32`.

ok,fix.
